sudo: false
language: scala

scala:
  - 2.12.8
  - 2.11.12

jdk:
  - openjdk11

before_install:
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.2.8 --install --fuzzy
  - gem i rubygems-update -v '<3' && update_rubygems
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues
  - sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "tbrown1979/totp4s" && sbt ++$TRAVIS_SCALA_VERSION publish
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "tbrown1979/totp4s" && test $TRAVIS_SCALA_VERSION == "2.12.16" && sbt docs/publishMicrosite

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt
